### ISSUE TITLE
Drop unused patches

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/libharu-feedstock#6]
This feedstock contains several patches:

https://github.com/conda-forge/libharu-feedstock/blob/fb947127e305446d6792dddf3955ffb9c2eef3ee/recipe/0001-skip-installing-if-directory.patch#L4

https://github.com/conda-forge/libharu-feedstock/blob/fb947127e305446d6792dddf3955ffb9c2eef3ee/recipe/0002-add-support-for-free-form.patch#L4

https://github.com/conda-forge/libharu-feedstock/blob/fb947127e305446d6792dddf3955ffb9c2eef3ee/recipe/0003-improve-small-number-writing-in-HPDF-FToA.patch#L4

However in PR ( https://github.com/conda-forge/libharu-feedstock/pull/3 ), these patches were no longer applied

Given this, should these patches be dropped? Or are they still needed and just need some reworking to apply?

cc @jschueller (in case you have any insights here)

**Comment by jschueller** [comment]
all these are applied in upstream recent versions and can be dropped now (I'm not maintainer here)

**Comment by xylar** [comment]
@jakirkham, do you want a PR to remove them now or should we just keep that in mind the next time a PR is needed for some other reason?

**Comment by xylar** [comment]
Assuming #7 works out, I've removed the patches in that PR.

**Comment by jakirkham** [comment]
Thank you both! 🙏
